from __future__ import annotations
import numpy as np
import pandas as pd
import streamlit as st

from cdc_platform.config.settings import settings
from cdc_platform.serving.jobs.nightly_pipeline import run_nightly_pipeline
from cdc_platform.modeling.early_warning.alert_rules import generate_alerts
from cdc_platform.modeling.seir.forecasting import forecast_cases_seir_with_uncertainty

st.set_page_config(page_title=settings.dashboard_title, layout="wide")
st.title("🧬 " + settings.dashboard_title)

with st.sidebar:
    st.header("Controls")
    start = st.date_input("Start date", value=pd.Timestamp.today().date() - pd.Timedelta(days=120))
    end = st.date_input("End date", value=pd.Timestamp.today().date())
    horizon = st.slider("Forecast horizon (days)", 7, 56, 28, 7)
    population = st.number_input("Population (for SEIR)", min_value=100_000, value=1_000_000, step=50_000)
    st.caption("Tip: run `cdc train-ml` to enable ML-driven alerts and dashboard risk tiles.")

master = run_nightly_pipeline(str(start), str(end))

st.subheader("Latest Surveillance Snapshot")
col1, col2, col3 = st.columns(3)
latest_date = pd.to_datetime(master["date"]).max().date().isoformat()
col1.metric("Latest date", latest_date)
col2.metric("Regions", master["region"].nunique())
col3.metric("Total cases (latest)", int(master[pd.to_datetime(master["date"]).dt.date.astype(str) == latest_date]["cases"].sum()))

st.divider()

regions = sorted(master["region"].unique().tolist())
region = st.selectbox("Region", regions, index=0)

g = master[master["region"] == region].copy()
g["date"] = pd.to_datetime(g["date"])
g = g.sort_values("date")

c1, c2 = st.columns([2, 1])

with c1:
    st.subheader("Cases trend")
    st.line_chart(g.set_index("date")["cases"])

with c2:
    st.subheader("Early warning")
    alerts = [a for a in generate_alerts(master) if a.region == region]
    if not alerts:
        st.success("No active alerts.")
    else:
        st.warning(f"{len(alerts)} alerts flagged")
        st.dataframe(pd.DataFrame([a.__dict__ for a in alerts]).sort_values(["date", "level"], ascending=[False, True]))

    # ML quick tile (if present)
    if "surge_prob_gb" in g.columns and "hosp_next7_pred" in g.columns:
        latest_row = g.tail(1)
        if not latest_row.empty and pd.notna(latest_row["surge_prob_gb"].iloc[0]):
            st.subheader("ML risk (latest)")
            st.metric("Surge probability (GB)", f"{latest_row['surge_prob_gb'].iloc[0]*100:.1f}%")
            st.metric("Hosp in 7d (pred)", f"{latest_row['hosp_next7_pred'].iloc[0]:.1f}")
        else:
            st.info("ML artifacts not found or no ML score for latest date. Run: `cdc train-ml`")

st.divider()

st.subheader("SEIR Forecast with Uncertainty Bands")
out = forecast_cases_seir_with_uncertainty(
    g["cases"],
    pop=int(population),
    horizon_days=int(horizon),
    n_samples=250,
    beta_sd_frac=0.15,
    quantiles=(0.1, 0.5, 0.9),
)

hist_idx = g["date"]
fut_idx = pd.date_range(hist_idx.max() + pd.Timedelta(days=1), periods=horizon, freq="D")

q10_hist = out["history"][0.1]
q50_hist = out["history"][0.5]
q90_hist = out["history"][0.9]

q10_fut = out["forecast"][0.1]
q50_fut = out["forecast"][0.5]
q90_fut = out["forecast"][0.9]

# Build chart tables (Streamlit line_chart can’t do bands directly; we show three lines)
hist_df = pd.DataFrame({"date": hist_idx, "q10 (best case)": q10_hist, "q50 (most likely)": q50_hist, "q90 (worst case)": q90_hist}).set_index("date")
fut_df = pd.DataFrame({"date": fut_idx, "q10 (best case)": q10_fut, "q50 (most likely)": q50_fut, "q90 (worst case)": q90_fut}).set_index("date")
all_df = pd.concat([hist_df, fut_df], axis=0)

st.metric("Estimated R0 (rough)", round(float(out["rt0_est"]), 2))
st.line_chart(all_df[["q10 (best case)", "q50 (most likely)", "q90 (worst case)"]])

st.caption("Bands are generated by sampling transmission rate (beta) around SEIR calibration and re-simulating.")
